version: '3.8'

services:
  app:
    build: .
    container_name: tres-astronautas-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/tres-db
    networks:
      - tres-network
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - tres-network

volumes:
  mongo-data:

networks:
  tres-network: